### ISSUE TITLE
Checking if an input is available for application use

### ISSUE THREAD

**Issue by Rectus** [KhronosGroup/OpenXR-Docs#109]
The input device interaction profiles have some inputs that may not be available for application use, such as system buttons. Additionally runtimes that can act as intermediaries for other runtimes, such as SteamVR may take up additional inputs for their system functions, blocking the use of the input in applications. 

There does not currently seem to be any way of determining if an input is available for application use. It would be useful if either a way to query if an input is available was added, or some form of feedback from attempting to bind it to an action.

**Comment by rpavlik** [comment]
You can check and see if an action with a suggested binding for such a button is active, using the getActionState functions and the "isActive" field: for example here: https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XrActionStateBoolean

The bindings are just suggestions: if you suggest something for an unavailable button, the runtime might remap that for you. In any case, the paths marked as "may not be available for application use" are mainly included for completeness and to allow runtimes to develop their system UI software using OpenXR as well. If you're writing "regular" application software, it's probably best to assume these aren't available, and not suggest bindings for them.

Note that you should only be suggesting bindings that you have personally tested: don't suggest bindings for every controller type for completeness. Suggest and test your suggested bindings, and let the runtimes remap for other controllers. If an input doesn't work from one of your suggested bindings when you test it, don't suggest it. The use of isActive is actually mostly for other purposes, IIRC: things like "I lost focus due to dashboard UI" or "controller momentarily lost connection" or "this action has no valid binding, suggested or otherwise, so I shouldn't expect it to be triggered" or "there's a higher-priority action currently bound where this action was bound previously, so it won't be giving me data until the higher-priority binding ends"

The underlying principles of the suggested binding and interaction profile system are the following: Developers want to be able to test on their main platforms and specify how their actions should map to inputs on those controllers. However, runtimes want to be able to run software that may be unaware of their controller type, without triggering untested code, etc. By suggesting bindings for an interaction profile, you're telling the runtime that you're aware of some controller type, and further that you've actually tested out your bindings with that controller type. So, a runtime will only ever tell you (via interaction profile change event) that the active interaction profile is one of the ones you suggested: this is meant to avoid having untested code paths (because you tested all the controllers you're suggesting for). Behind the scenes, the runtime may remap from the closest-matching suggested interaction profile to some controller you've never heard of, or even to different inputs on one of your suggested controllers (if configured by a user - may be for accessibility reasons, etc), but that all stays (almost) entirely hidden inside the runtime, and you can just treat the controller like it is one of your tested ones.  (The "almost" is covering things like controller models, which can vary based on the *real* controller used rather than the interaction profile reported, but which have other mechanisms to make handling them uniform and opaque and avoid untested code paths. You'll never be told "this is an Index controller" if you're only suggesting for vive wands and oculus touch, but a real vive wand and real index controller might return different opaque controller model blobs that nonetheless are processed the same way in your application.)

Hope that helps you understand this recommendation! Let me know if it didn't and you want this reopened.

**Comment by Rectus** [comment]
Thanks for clarifying.

The main thing that caused me to think about this issue is a specific interaction with the Oculus Touch controllers and SteamVR. The left Touch controller has a menu button that gets co-opted by SteamVR for the dashboard, while remaining user accessible with the native Oculus runtime. The button is not marked with "may not be available for application use". This might cause issues with applications that use all buttons on the controller and expect all of them to be available. I guess the solution is to design applications in a more input agnostic way, but that may be difficult.

**Comment by rpavlik** [comment]
Oh, interesting. I didn't know that. I'll share this with the relevant folks who might want to have a think about that, etc.
