### ISSUE TITLE
[Proposal] A way to get devices properties

### ISSUE THREAD

**Issue by dav64** [KhronosGroup/OpenXR-Docs#110]
Would be useful to have a way to retrieve various properties of the physical devices _à la_ OpenVR

for example `xrGetFloatTrackedDeviceProperty(const XXX* device_identifier, const XXX* property_key, float* output)`

https://github.com/ValveSoftware/openvr/wiki/IVRSystem::GetTrackedDeviceProperty
https://github.com/ValveSoftware/openvr/blob/4c85abcb7f7f1f02adaf3812018c99fc593bc341/headers/openvr_api.cs#L4577

Would be useful for example to fetch battery level or brand / model of device

**Comment by rpavlik** [comment]
I believe previous discussion of battery level arrived at the conclusion that handling it was the system UI's responsibility, but for customized controller models or writing system UI using OpenXR, the group might be open to revisiting that conclusion. You're also welcome to propose a vendor extension for battery level, though it probably wouldn't make sense to merge without at least one runtime onboard for implementing it.

In general, things like "fetching brand/model of device" run counter to the goals and methods of OpenXR: the principle is to make it so that you don't have to know these details to write software, and thus whatever you write can run on systems you never knew about and systems that come out after your software is released. Similarly I don't think a generic interface like OpenVR has really fits with OpenXR here: if a given property doesn't fit in the actions system (which provides re-bindability, etc), I suspect the WG is more likely to prefer smaller, more precise extensions that address the challenges of software portability for each property or class of properties.

If you have specific use cases for the device identity information, do let us know so that we can work on solving how to meet those use cases without requiring hardware-specific code. The action and interaction profile system is a key example: see the "principles" section of my response here for details: https://github.com/KhronosGroup/OpenXR-Docs/issues/109#issuecomment-1007768616  As another example, there are extensions related to displayable controller models that provide an asset at runtime without requiring you to know what specific controller is being used, etc: they provide a sufficiently opaque and uniform output that all models should use the same code path. There's also the case of virtual production, where creation and usage of the software is more closely intertwined than consumer/commercial software with distinct developers and users: they might not care the specific brand/model of the devices but would want to be able to persistently associate a given device with some role (like our top level user paths, /user/hands/left, etc, but a much larger space of roles) without hardcoding a serial number, and with the ability to change that association later in case of dead battery, hardware failure, etc. (This is a much harder one to crack than the controller model thing, but there's already an HTC Vive Tracker experimental extension attempting it)

I'll close this for now because I don't foresee a general "xrGetFloatTrackedDeviceProperty" being added, but please feel free to open an issue for specific use cases (battery level, etc) that matter to you and that can be tackled one at a time by the WG. You're welcome to submit your own vendor extension as well, see https://www.khronos.org/registry/OpenXR/#extprocess - While it mostly only makes sense to do so if you work on a runtime, if other runtime vendors show interest in implementing, or if your extension can be implemented entirely in an API layer, I will say from experience that it's much easier for a group, including the OpenXR WG participants, to make progress on a solution if there's a concrete usable proposal to refine. (That is, for example, it might not be anyone's priority to write a battery level extension right now, but if you write up the spec text and XML for it - see the style guide and existing extensions - you might find that there are folks happy that you did the first step in the specification and willing to implement. The runtime I work on, Monado, is open source and great for testing out these kinds of ideas with, too, just as a shameless plug :D that's a big part of the value it provides to the group and the broader XR community.)
