### ISSUE TITLE
OpenXR does NOT work with Shadow VR (Beta)

### ISSUE THREAD

**Issue by Thewalk4756** [KhronosGroup/OpenXR-Docs#112]
Hello! I am a virtual reality gamer, and I use a streaming service known as "Shadow VR" to play virtual reality games. It streams a high end PC to my oculus quest headset so I can play SteamVR games just from my quest.

However, I recently installed 2 games that use OpenXR, and I have found the experience to be completely unplayable for both of these games and they both have the same exact issue.

After booting up a game, my hands spawn below my floor, and have inaccurate movements. The rotation of my hands is accurate, but when I try to move my hands from left to right for example, it is not accurate and does not show my hands moving the correct direction or distance. They stay below my floor and do not work, and I am basically unable to do anything.

Spent around 19 USD on a game thinking it would work, but unfortunately the issue with the game is not an issue from the game itself, but from OpenXR.

If any more details are needed, please let me know! I'm hoping this is fixed in the future, as shadow vr is the only way I'm able to play VR!

**Comment by rpavlik** [comment]
Unfortunately, this repo is for the folks who work on developing the OpenXR spec itself, not any OpenXR software that you're using. My hunch is that the problem is either in Shadow VR or SteamVR, not sure which, but it's not here. Get in touch with the people behind that software (most likely Shadow VR, since SteamVR is tested to be conformant and something like this would break the conformance tests) for help with your issue.

(Is there a reason you aren't using Oculus Link to plug your quest right into your PC? The Oculus OpenXR runtime is conformant and widely used in this mode. Some folks use Virtual Desktop instead to do a similar remote thing that you are describing, but I have no experience with any of them)

Out of curiousity, what OpenXR games did you install? This is just me being nosy, not everyone tells me when they ship an OpenXR game, so I only know of a few (MS flight sim, minecraft, etc)
