### ISSUE TITLE
ViewConfigurationProperties viewConfigurationType member is unnecessary

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#13]
An `XrViewConfigurationProperties` is obtained by passing a `XrViewConfigurationType` to `xrGetViewConfigurationProperties`. Having it return the same value you passed in back to you is both unnecessary (you necessarily already have that information) and confusing (my first thought was "wait, can this be something else?"). If that is indeed the only function of the member, it should be removed; otherwise, the cases where it can convey new information should be illustrated.

**Comment by Ralith** [comment]
Looks like this was missed for 1.0 :(

**Comment by brycehutchings** [comment]
We discussed it and there were differing opinions so it was kept. There is a perspective that structures should give back the information that identifies them, which could result in keeping fewer objects around for the lifetime of an app (e.g. no need to keep track of the desired XrViewportConfigurationType if the app keeps the XrViewConfigurationProperties around instead). xrGetSystemProperties also follows this pattern where XrSystemProperties includes an XrSystemId which is simply the systemId that was passed in. Initially I too found it confusing since it provided no new information and made me question why it was there, but I think we can mitigate confusion with better documentation.

**Comment by rpavlik** [comment]
Closing as it is too late to remove. If there's a suggestion how to phrase a clarification, please submit a pull request and we'll be happy to look at it.
