### ISSUE TITLE
Incorrect constness on XrEventDataBuffer::next

### ISSUE THREAD

**Issue by Ralith** [KhronosGroup/OpenXR-Docs#28]
The `next` field of `XrEventDataBuffer` [is marked `const`](https://github.com/KhronosGroup/OpenXR-Docs/blob/master/include/openxr/openxr.h#L456). This is an output struct for `xrPollEvent`, so extension structs used with it will presumably be written to.

**Comment by yl-msft** [comment]
Interesting... this seems applicable to every XrEventData* structs, including base header and other concrete event types.

**Comment by brycehutchings** [comment]
My understanding is xrPollEvent will set 'next' to point to data inside the event buffer if there is a desire to include an extension struct on an existing event structure. I don't think the intent was for apps to set 'next' (xrPollEvent is special in this way). In this regard, I don't think the "const" causes any problems because the runtime is setting the pointer rather than the memory that the pointer points to.

I do think marking it non-const would be preferred, since the app owns the memory though.

**Comment by rpavlik** [comment]
This one is a special case: when you get it back from the runtime, it's no longer an XrEventDataBuffer, but one (or possibly more, in a next chain, but in the originally-used memory space) XrEventBaseHeader-derived type.

I'm not sure if changing the constness of this is very helpful, since this is a weird case anyway, nor if it's something that will break the world if we do it now (instead of back when this was reported or before). I think this may just be a wart we have to live with.

**Comment by Ralith** [comment]
If the value of the `next` field when passed in is never, and will never be, dereffed by the runtime, then the current behavior makes sense, though it's definitely a bit unique. I don't think any change is needed here; there's nothing wrong with a const pointer to mutable memory, and it's semantically appropriate for data generated by the runtime to be addressed that way, since mutating it in-place doesn't accomplish much.
