### ISSUE TITLE
OS support

### ISSUE THREAD

**Issue by ShalokShalom** [KhronosGroup/OpenXR-Docs#33]
hi :hugs: 

I am missing some information on the start page about os support. is this something that I can use to utilize windows VR on Linux?

since it is a coss platform abstraction layer, it should mean that I can use every supported goggle on each supported OS

that would be superb, why are you hiding this feature on your homepage?

**Comment by rpavlik** [comment]
Well, that would be great, but that's not quite what OpenXR does. OpenXR, as a standard, provides a uniform interface for an application to be run without code changes across different headsets and runtimes. You still need the application compiled for a given platform - Windows emulation, etc. is out of scope for OpenXR. And you still need a runtime on your chosen platform that supports the headset you want to use.

Since you've mentioned Linux, I'll direct you to Collabora's open source work-in-progress OpenXR runtime, Monado, which runs on Linux on a variety of headsets. https://gitlab.freedesktop.org/monado/monado

Thanks for your interest!

**Comment by ShalokShalom** [comment]
So, an application that supports OpenXR, supports all platforms?

**Comment by rpavlik** [comment]
No, it supports all OpenXR-supported headsets on whatever platform the application supports. It doesn't get around the need to build an application for a given operating system, etc.

**Comment by ShalokShalom** [comment]
So its simply a uniform platform to target all OpenXR supported Headsets at once? Thanks a lot
