### ISSUE TITLE
Section 10.1: xrEnumerateSwapchainImages images parameter inconsistency

### ISSUE THREAD

**Issue by pH5** [KhronosGroup/OpenXR-Docs#5]
> 10.1. Swapchain Image Management
> Parameter Descriptions
> * `images` is a pointer to an array of graphics API-specific `XrSwapchainImage` structures based off of `XrSwapchainImageBaseHeader`. It **can** be `NULL` if `imageCapacityInput` is `0`.

vs

> Valid Usage (Implicit)
> * If `imageCapacityInput` is not `0`, `images` **must** be a pointer to an array of `imageCapacityInput` `XrSwapchainImageBaseHeader` structures

`images` should never be a pointer to an array of `XrSwapchainImageBaseHeader` structures, it must be an array of (larger) graphics API-specific structures that each start with a base header.

Should this state that they all must be of the same type?

**Comment by brycehutchings** [comment]
Agreed they should be homogeneous in type and never the literal `XrSwapchainImageBaseHeader` type.

**Comment by rpavlik** [comment]
Fixed in 1.0.0 (valid usage generation needed adjustment to handle these types of parameters): now says "If `imageCapacityInput` is not `0`, images must be a pointer to an array of `imageCapacityInput` XrSwapchainImageBaseHeader-based structures. See also: XrSwapchainImageD3D11KHR, XrSwapchainImageOpenGLESKHR, XrSwapchainImageD3D12KHR, XrSwapchainImageOpenGLKHR, XrSwapchainImageVulkanKHR"
