### ISSUE TITLE
Why doesn't XrCompositionLayerColorScaleBiasKHR `structextend` the children of XrCompositionLayerBaseHeader?

### ISSUE THREAD

**Issue by expipiplus1** [KhronosGroup/OpenXR-Docs#67]
At the moment it seems as though there's no valid place to use XrCompositionLayerColorScaleBiasKHR. I'm forbidden for extending any structs other than XrCompositionLayerBaseHeader with it. But I can't use XrCompositionLayerBaseHeader directly!

A simple fix for (what I think is the intended behaviour) would be to add the children of XrCompositionLayerBaseHeader to the `structextends` attribute of XrCompositionLayerColorScaleBiasKHR

**Comment by rpavlik** [comment]
So probably the easier solution is making it clear that any struct extending XrCompositionLayerBaseHeader can also extend its derived structs? Is this just a markup thing in the XML, or is there an issue in the output spec text?

**Comment by expipiplus1** [comment]
Sorry for the lateness of my reply.

From my end, it's just about the XML. Without this in there I have to special case a couple of things in my generator.

**Comment by rpavlik** [comment]
So parentstruct is a substitution relationship: because each layer has parentstruct XrCompositionLayerBaseHeader, you can use each layer type anywhere XrCompositionLayerBaseHeader is mentioned. A structextends of XrCompositionLayerBaseHeader implies a structextends of the set of layers with parentstruct=XrCompositionLayerBaseHeader.  I'm pretty sure our validation layer (generated) already check this, etc. so I think the information is there and intended to be generalizable. You shouldn't need to special case that - there are other instances where there are BaseHeader structs and things that extend them. The recent Facebook extensions about layer properties come to mind.

I'm going to close this since I think the information is already there and it's just a matter of how to interpret the XML. Let me know if my explanation above missed anything for you.
